<?php

namespace AppBundle\Repository;

/**
 * ArttRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArttRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $mois
     * @param $annee
     * @return mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getSommeJoursMoisCourant($mois, $annee)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT SUM(artt.exceptionnelAquis) as sommeExceptionnelAquis, SUM(artt.exceptionnelPris) as sommeExceptionnelPris,
                        SUM(artt.congesAquis) as sommeCongesAquis, SUM(artt.congesPris) as sommeCongesPris,
                        SUM(artt.arttAquis) as sommeArttAquis, SUM(artt.arttPris) as sommeArttPris
                FROM AppBundle:Artt artt
                WHERE artt.annee = :annee
                AND artt.mois <= :mois'
            )
            ->setParameter('annee', $annee)
            ->setParameter('mois', $mois);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
